-- Bootstrap de estructuras para ciclo de vida de torneos en esquema en espanol.
-- Ejecutar antes del RPC, solo una vez.

create table if not exists public.torneo_estado (
  id bigint generated by default as identity primary key,
  torneo_id bigint not null,
  categoria text not null,
  grupo text not null,
  estado text not null default 'RECRUITING'
    check (estado in ('RECRUITING', 'LOCKED', 'IN_PROGRESS')),
  max_participantes integer not null default 8,
  current_participantes integer not null default 0,
  sorteo_realizado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'uq_torneo_estado_scope'
  ) then
    if exists (
      select 1
      from pg_class
      where relname = 'uq_torneo_estado_scope'
        and relkind = 'i'
    ) then
      alter table public.torneo_estado
        add constraint uq_torneo_estado_scope
        unique using index uq_torneo_estado_scope;
    else
      alter table public.torneo_estado
        add constraint uq_torneo_estado_scope
        unique (torneo_id, categoria, grupo);
    end if;
  end if;
end $$;

create index if not exists idx_torneo_estado_estado
  on public.torneo_estado (estado);
