-- ============================================================
-- Crea las tablas torneo_jugadores y partidos si no existen.
--
-- Estas tablas faltaban en el set de migraciones: sólo había
-- ALTER TABLE IF EXISTS, que hace nada si la tabla no existe.
-- Ejecutar en Supabase SQL Editor → será idempotente.
-- ============================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------
-- TABLA: torneo_jugadores
-- Almacena a cada jugador inscripto y aprobado en un grupo
-- dentro de un torneo, junto con sus estadísticas.
-- ----------------------------------------------------------
create table if not exists public.torneo_jugadores (
  id              bigint generated by default as identity primary key,
  torneo_id       bigint not null,
  perfil_id       uuid   not null,
  categoria       text   not null,
  grupo           text   not null,
  puntos          integer not null default 0,
  partidos_jugados integer not null default 0,
  sets_ganados    integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint uq_torneo_jugadores_scope
    unique (torneo_id, perfil_id, categoria, grupo)
);

create index if not exists idx_torneo_jugadores_scope
  on public.torneo_jugadores (torneo_id, categoria, grupo, perfil_id);

create index if not exists idx_torneo_jugadores_perfil
  on public.torneo_jugadores (perfil_id);

-- updated_at automático
create or replace function public.set_torneo_jugadores_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_torneo_jugadores_updated_at on public.torneo_jugadores;
create trigger trg_torneo_jugadores_updated_at
  before update on public.torneo_jugadores
  for each row execute function public.set_torneo_jugadores_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'torneo_jugadores'
  ) then
    alter publication supabase_realtime add table public.torneo_jugadores;
  end if;
end $$;


-- ----------------------------------------------------------
-- TABLA: partidos
-- Almacena cada cruce del fixture de un torneo.
-- El RPC de inscripción los crea automáticamente cuando
-- el grupo alcanza el cupo máximo.
-- ----------------------------------------------------------
create table if not exists public.partidos (
  id              uuid primary key default gen_random_uuid(),
  torneo_id       bigint,
  categoria       text,
  grupo           text,
  jornada         integer not null default 1,
  jugador1_id     uuid,
  jugador2_id     uuid,
  fecha_programada timestamptz,
  resultado       text not null default 'PENDIENTE',
  estado          text not null default 'programado',
  ganador_id      uuid,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists uq_partidos_id
  on public.partidos (id);

create index if not exists idx_partidos_torneo_scope
  on public.partidos (torneo_id, categoria, grupo, jornada, estado);

create index if not exists idx_partidos_torneo_jugadores
  on public.partidos (torneo_id, categoria, grupo, jugador1_id, jugador2_id);

create unique index if not exists uq_partidos_programados_scope_pair
  on public.partidos (
    torneo_id,
    categoria,
    grupo,
    jornada,
    least(jugador1_id, jugador2_id),
    greatest(jugador1_id, jugador2_id)
  )
  where estado = 'programado'
    and jugador1_id is not null
    and jugador2_id is not null;

-- updated_at automático
create or replace function public.set_partidos_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_partidos_updated_at on public.partidos;
create trigger trg_partidos_updated_at
  before update on public.partidos
  for each row execute function public.set_partidos_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'partidos'
  ) then
    alter publication supabase_realtime add table public.partidos;
  end if;
end $$;


-- ----------------------------------------------------------
-- COLUMNA whatsapp en perfiles (si no existe)
-- Necesaria para mostrar el botón de contacto del rival.
-- ----------------------------------------------------------
alter table if exists public.perfiles
  add column if not exists whatsapp text;

-- ----------------------------------------------------------
-- DIAGNÓSTICO: Verificar estado real de las tablas
-- Copiar y pegar en Supabase SQL Editor para confirmar.
-- ----------------------------------------------------------
-- SELECT
--   'torneo_jugadores' AS tabla,
--   COUNT(*) AS filas
-- FROM public.torneo_jugadores
-- UNION ALL
-- SELECT 'partidos', COUNT(*) FROM public.partidos
-- UNION ALL
-- SELECT 'torneo_estado', COUNT(*) FROM public.torneo_estado
-- UNION ALL
-- SELECT 'inscripciones_torneo', COUNT(*) FROM public.inscripciones_torneo;
