-- ============================================================
-- Tabla maestra de torneos.
-- Antes estaban hardcodeados en el frontend (Tournaments.tsx).
-- A partir de esta migración, el frontend los carga desde aquí.
-- ============================================================

create table if not exists public.torneos (
  id         bigint generated by default as identity primary key,
  titulo     text not null,
  subtitulo  text not null,  -- actúa como "categoria" en torneo_estado / torneo_jugadores / partidos
  fecha_inicio date,
  fecha_fin    date,
  imagen_url   text,
  activo       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- updated_at automático
drop trigger if exists trg_torneos_updated_at on public.torneos;
create trigger trg_torneos_updated_at
  before update on public.torneos
  for each row execute function public.set_updated_at();

-- RLS: cualquier visitante puede leer, solo admin puede escribir
alter table public.torneos enable row level security;

drop policy if exists "torneos_select_todos" on public.torneos;
create policy "torneos_select_todos"
  on public.torneos for select
  using (true);

drop policy if exists "torneos_insert_admin" on public.torneos;
create policy "torneos_insert_admin"
  on public.torneos for insert
  with check (public.is_admin());

drop policy if exists "torneos_update_admin" on public.torneos;
create policy "torneos_update_admin"
  on public.torneos for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "torneos_delete_admin" on public.torneos;
create policy "torneos_delete_admin"
  on public.torneos for delete
  using (public.is_admin());

-- ============================================================
-- Datos iniciales: los 5 torneos que existían hardcodeados.
-- Los IDs coinciden con los torneo_id usados en torneo_estado,
-- torneo_jugadores, partidos, etc.
-- ============================================================
insert into public.torneos (id, titulo, subtitulo, fecha_inicio, fecha_fin, imagen_url) values
(
  1,
  'Caballeros Singles - 3ra Categoría',
  'Singles Caballeros',
  '2026-03-10',
  '2026-03-15',
  '/images/tournament-default.jpg'
),
(
  2,
  'Caballeros Singles - 2da Categoría',
  'Singles Caballeros',
  '2026-03-12',
  '2026-03-18',
  '/images/tournament-2.jpg'
),
(
  3,
  'Caballeros Singles - Intermedia',
  'Singles Caballeros',
  '2026-03-20',
  '2026-03-25',
  '/images/tournament-3.jpg'
),
(
  4,
  'Mujeres Singles - Categoría Libre',
  'Singles Damas',
  '2026-04-08',
  '2026-04-14',
  '/images/tournament-4.jpg'
),
(
  5,
  'Torneo de Dobles Mixto/Libre',
  'Dobles Mixtos',
  '2026-04-01',
  '2026-04-05',
  '/images/tournament-5.jpg'
)
on conflict (id) do nothing;

-- ============================================================
-- Para agregar torneos nuevos en el futuro (sin tocar código):
--   insert into public.torneos (titulo, subtitulo, fecha_inicio, fecha_fin, imagen_url)
--   values ('Nombre del Torneo', 'Categoría', '2026-05-01', '2026-05-10', '/images/tournament-X.jpg');
--
-- Para imágenes dinámicas, sube a Supabase Storage o usa rutas locales en public/images/
-- El frontend los va a mostrar automáticamente al cargar la página.
-- ============================================================
