-- ============================================================
-- Reconstrucción completa de la base de datos TuBarrio
-- ============================================================

-- 1. Tabla perfiles (fundamental)
CREATE TABLE IF NOT EXISTS public.perfiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  nombre_completo TEXT,
  whatsapp TEXT,
  rol TEXT DEFAULT 'jugador',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla torneos
CREATE TABLE IF NOT EXISTS public.torneos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  titulo TEXT NOT NULL,
  subtitulo TEXT,
  fecha_inicio DATE,
  fecha_fin DATE,
  imagen_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla torneo_estado
CREATE TABLE IF NOT EXISTS public.torneo_estado (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  torneo_id BIGINT UNIQUE NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  estado TEXT DEFAULT 'inscripciones_abiertas',
  current_participantes INTEGER DEFAULT 0,
  max_participantes_total INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla inscripciones_torneo
CREATE TABLE IF NOT EXISTS public.inscripciones_torneo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id),
  perfil_id UUID NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  estado TEXT NOT NULL DEFAULT 'pendiente_revision'
    CHECK (estado IN ('pendiente_revision', 'pagado_aprobado', 'rechazado')),
  monto NUMERIC(10,2) NOT NULL,
  moneda TEXT NOT NULL DEFAULT 'ARS',
  metodo_pago TEXT NOT NULL DEFAULT 'transferencia_alias',
  categoria TEXT,
  grupo TEXT,
  alias_destino TEXT NOT NULL,
  whatsapp_destino TEXT NOT NULL,
  referencia_manual TEXT,
  comprobante_url TEXT,
  aprobado_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  aprobado_en TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_inscripcion_torneo_perfil UNIQUE (torneo_id, perfil_id)
);

-- 5. Tabla torneo_jugadores
CREATE TABLE IF NOT EXISTS public.torneo_jugadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  perfil_id UUID NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  categoria TEXT,
  grupo TEXT,
  puntos INTEGER DEFAULT 0,
  partidos_jugados INTEGER DEFAULT 0,
  sets_ganados INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_torneo_jugador UNIQUE (torneo_id, perfil_id)
);

-- 6. Tabla partidos
CREATE TABLE IF NOT EXISTS public.partidos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  jugador1_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  jugador2_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  jornada INTEGER,
  ronda INTEGER,
  bracket_tipo TEXT, -- 'round_robin', 'eliminacion_directa', 'grupo'
  estado TEXT DEFAULT 'programado',
  resultado_jugador1 INTEGER,
  resultado_jugador2 INTEGER,
  sets_jugador1 INTEGER DEFAULT 0,
  sets_jugador2 INTEGER DEFAULT 0,
  ganador_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  fecha_programada TIMESTAMPTZ,
  confirmado_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  siguiente_partido_id UUID REFERENCES public.partidos(id) ON DELETE SET NULL,
  external_match_key TEXT,
  stage_name TEXT, -- Para nombres de etapas: 'Final', 'Semifinal', etc.
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabla torneo_grupos
CREATE TABLE IF NOT EXISTS public.torneo_grupos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  codigo TEXT,
  nombre TEXT,
  categoria TEXT,
  grupo_base_id UUID REFERENCES public.torneo_grupos(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabla torneo_configuracion
CREATE TABLE IF NOT EXISTS public.torneo_configuracion (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  categoria TEXT,
  formato TEXT DEFAULT 'round_robin',
  max_participantes_por_grupo INTEGER DEFAULT 4,
  numero_grupos INTEGER,
  min_participantes_por_grupo INTEGER,
  max_participantes_total INTEGER,
  clasificados_por_grupo INTEGER NOT NULL DEFAULT 2,
  crear_playoffs_eliminacion_directa BOOLEAN NOT NULL DEFAULT false,
  grupo_base TEXT,
  partidos_por_jugador INTEGER DEFAULT 3,
  grupo_base_id UUID REFERENCES public.torneo_grupos(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabla torneo_propuestas_partido
CREATE TABLE IF NOT EXISTS public.torneo_propuestas_partido (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  partido_id UUID REFERENCES public.partidos(id) ON DELETE CASCADE,
  jugador1_id UUID NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  jugador2_id UUID NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  fecha_propuesta TIMESTAMPTZ NOT NULL,
  estado TEXT DEFAULT 'pendiente',
  propuesta_por UUID NOT NULL REFERENCES public.perfiles(id) ON DELETE CASCADE,
  respuesta_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  debe_confirmar_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  fecha_respuesta TIMESTAMPTZ,
  mensaje_propuesta TEXT,
  mensaje_respuesta TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_propuesta_pair UNIQUE (torneo_id, jugador1_id, jugador2_id, estado)
);

-- 10. Tabla torneo_partidos_historial
CREATE TABLE IF NOT EXISTS public.torneo_partidos_historial (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  partido_id UUID NOT NULL REFERENCES public.partidos(id) ON DELETE CASCADE,
  torneo_id BIGINT NOT NULL REFERENCES public.torneos(id) ON DELETE CASCADE,
  jugador1_id UUID NOT NULL REFERENCES public.perfiles(id),
  jugador2_id UUID NOT NULL REFERENCES public.perfiles(id),
  resultado_jugador1 INTEGER,
  resultado_jugador2 INTEGER,
  sets_jugador1 INTEGER DEFAULT 0,
  sets_jugador2 INTEGER DEFAULT 0,
  ganador_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  fecha_registro TIMESTAMPTZ DEFAULT NOW(),
  registrado_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  external_match_key TEXT,
  CONSTRAINT uq_partido_historial UNIQUE (partido_id)
);

-- 11. Tabla marketplace_servicios
CREATE TABLE IF NOT EXISTS public.marketplace_servicios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10,2),
  categoria TEXT,
  proveedor_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
  contacto_whatsapp TEXT,
  contacto_email TEXT,
  imagen_url TEXT,
  estado TEXT DEFAULT 'activo',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices importantes
CREATE INDEX IF NOT EXISTS idx_perfiles_email ON public.perfiles(email);
CREATE INDEX IF NOT EXISTS idx_perfiles_rol ON public.perfiles(rol);
CREATE INDEX IF NOT EXISTS idx_torneos_fecha_inicio ON public.torneos(fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_torneo_estado_torneo ON public.torneo_estado(torneo_id);
CREATE INDEX IF NOT EXISTS idx_inscripciones_perfil ON public.inscripciones_torneo(perfil_id);
CREATE INDEX IF NOT EXISTS idx_inscripciones_torneo ON public.inscripciones_torneo(torneo_id);
CREATE INDEX IF NOT EXISTS idx_inscripciones_estado ON public.inscripciones_torneo(estado);
CREATE INDEX IF NOT EXISTS idx_torneo_jugadores_torneo ON public.torneo_jugadores(torneo_id);
CREATE INDEX IF NOT EXISTS idx_torneo_jugadores_perfil ON public.torneo_jugadores(perfil_id);
CREATE INDEX IF NOT EXISTS idx_partidos_torneo ON public.partidos(torneo_id);
CREATE INDEX IF NOT EXISTS idx_partidos_jugadores ON public.partidos(jugador1_id, jugador2_id);
CREATE INDEX IF NOT EXISTS idx_partidos_bracket ON public.partidos(bracket_tipo, ronda);
CREATE INDEX IF NOT EXISTS idx_partidos_stage_name ON public.partidos(stage_name);

-- Enable Row Level Security
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_estado ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inscripciones_torneo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_jugadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_propuestas_partido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneo_partidos_historial ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_servicios ENABLE ROW LEVEL SECURITY;

-- Políticas RLS básicas
CREATE POLICY "Perfiles select para todos" ON public.perfiles FOR SELECT USING (true);
CREATE POLICY "Perfiles update propio" ON public.perfiles FOR UPDATE USING (id = auth.uid());
CREATE POLICY "Torneos select para todos" ON public.torneos FOR SELECT USING (true);
CREATE POLICY "Partidos select para todos" ON public.partidos FOR SELECT USING (true);
CREATE POLICY "Torneo jugadores select para participantes" ON public.torneo_jugadores FOR SELECT USING (torneo_id IN (SELECT torneo_id FROM public.torneo_jugadores WHERE perfil_id = auth.uid()));

-- Función auxiliar para actualizar timestamps
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para updated_at
CREATE TRIGGER trigger_perfiles_updated_at
  BEFORE UPDATE ON public.perfiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trigger_torneos_updated_at
  BEFORE UPDATE ON public.torneos
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trigger_partidos_updated_at
  BEFORE UPDATE ON public.partidos
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trigger_inscripciones_updated_at
  BEFORE UPDATE ON public.inscripciones_torneo
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- Insertar torneo de ejemplo
INSERT INTO public.torneos (id, titulo, subtitulo, fecha_inicio, fecha_fin)
VALUES (1, 'Abierto de Tenis TuBarrio', '2da Categoría - Singles', '2026-05-01', '2026-05-31')
ON CONFLICT (id) DO NOTHING;

-- Insertar estado del torneo
INSERT INTO public.torneo_estado (torneo_id, estado, max_participantes_total)
VALUES (1, 'en_curso', 16)
ON CONFLICT (torneo_id) DO NOTHING;

-- Insertar jugadores de ejemplo
INSERT INTO public.perfiles (id, nombre_completo, email, whatsapp) VALUES
  ('00000000-0000-0000-0000-000000000001', 'Carlos Rodríguez', 'carlos@test.com', '11-1234-5678'),
  ('00000000-0000-0000-0000-000000000002', 'Martín González', 'martin@test.com', '11-2345-6789'),
  ('00000000-0000-0000-0000-000000000003', 'Diego Sánchez', 'diego@test.com', '11-3456-7890'),
  ('00000000-0000-0000-0000-000000000004', 'Lucas Fernández', 'lucas@test.com', '11-4567-8901'),
  ('00000000-0000-0000-0000-000000000005', 'Pablo Martínez', 'pablo@test.com', '11-5678-9012'),
  ('00000000-0000-0000-0000-000000000006', 'Roberto López', 'roberto@test.com', '11-6789-0123'),
  ('00000000-0000-0000-0000-000000000007', 'Fernando Torres', 'fernando@test.com', '11-7890-1234'),
  ('00000000-0000-0000-0000-000000000008', 'Javier Castro', 'javier@test.com', '11-8901-2345')
ON CONFLICT (id) DO NOTHING;

-- Insertar jugadores en el torneo
INSERT INTO public.torneo_jugadores (torneo_id, perfil_id, categoria, grupo)
SELECT 1, id, 'Segunda', 'A'
FROM public.perfiles
WHERE id::TEXT LIKE '00000000-0000-0000-0000-000000000%'
ON CONFLICT (torneo_id, perfil_id) DO NOTHING;

-- Actualizar contador de participantes
UPDATE public.torneo_estado 
SET current_participantes = (SELECT COUNT(*) FROM public.torneo_jugadores WHERE torneo_id = 1)
WHERE torneo_id = 1;

-- Insertar partidos de bracket de ejemplo con diferentes rondas
INSERT INTO public.partidos (torneo_id, jugador1_id, jugador2_id, jornada, ronda, bracket_tipo, estado, stage_name) VALUES
  -- Final (ronda 4)
  (1, '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', 7, 4, 'eliminacion_directa', 'programado', 'Final'),
  -- Semifinales (ronda 3)
  (1, '00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000004', 6, 3, 'eliminacion_directa', 'programado', 'Semifinal'),
  (1, '00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000006', 6, 3, 'eliminacion_directa', 'programado', 'Semifinal'),
  -- Cuartos de final (ronda 2)
  (1, '00000000-0000-0000-0000-000000000007', '00000000-0000-0000-0000-000000000008', 5, 2, 'eliminacion_directa', 'programado', 'Cuartos de Final'),
  (1, '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000003', 5, 2, 'eliminacion_directa', 'programado', 'Cuartos de Final'),
  (1, '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000005', 5, 2, 'eliminacion_directa', 'programado', 'Cuartos de Final'),
  (1, '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000007', 5, 2, 'eliminacion_directa', 'programado', 'Cuartos de Final'),
  -- Octavos de final (ronda 1)
  (1, '00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000008', 4, 1, 'eliminacion_directa', 'programado', 'Octavos de Final');

-- Base de datos reconstruida exitosamente
-- Torneo: Abierto de Tenis TuBarrio
-- Jugadores: 8 participantes
-- Partidos: 10 partidos de bracket
-- Rondas: Octavos, Cuartos, Semifinales, Final
