-- ============================================================
-- Verificar y corregir estructura de inscripciones
-- ============================================================

-- 1. Verificar si existe la tabla inscripciones_torneo
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'inscripciones_torneo' AND table_schema = 'public') THEN
        RAISE NOTICE 'La tabla inscripciones_torneo existe';
    ELSE
        RAISE NOTICE 'La tabla inscripciones_torneo NO existe - creándola';
    END IF;
END $$;

-- 2. Crear tabla inscripciones_torneo si no existe
CREATE TABLE IF NOT EXISTS public.inscripciones_torneo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id BIGINT NOT NULL,
    perfil_id UUID NOT NULL,
    estado TEXT NOT NULL DEFAULT 'pendiente_revision',
    monto INTEGER NOT NULL DEFAULT 0,
    moneda TEXT NOT NULL DEFAULT 'ARS',
    metodo_pago TEXT NOT NULL DEFAULT 'transferencia_alias',
    categoria TEXT,
    grupo TEXT,
    alias_destino TEXT,
    whatsapp_destino TEXT,
    referencia_manual TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT fk_inscripciones_torneo FOREIGN KEY (torneo_id) REFERENCES public.torneos(id) ON DELETE CASCADE,
    CONSTRAINT fk_inscripciones_perfil FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE,
    CONSTRAINT uq_torneo_perfil UNIQUE (torneo_id, perfil_id)
);

-- 3. Habilitar RLS
ALTER TABLE public.inscripciones_torneo ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas RLS si no existen
DROP POLICY IF EXISTS "Users can view their own tournament enrollments" ON public.inscripciones_torneo;
CREATE POLICY "Users can view their own tournament enrollments" ON public.inscripciones_torneo
    FOR SELECT USING (auth.uid()::text = perfil_id::text);

DROP POLICY IF EXISTS "Users can insert their own tournament enrollments" ON public.inscripciones_torneo;
CREATE POLICY "Users can insert their own tournament enrollments" ON public.inscripciones_torneo
    FOR INSERT WITH CHECK (auth.uid()::text = perfil_id::text);

DROP POLICY IF EXISTS "Users can update their own pending enrollments" ON public.inscripciones_torneo;
CREATE POLICY "Users can update their own pending enrollments" ON public.inscripciones_torneo
    FOR UPDATE USING (auth.uid()::text = perfil_id::text AND estado = 'pendiente_revision');

-- 5. Crear índices si no existen
CREATE INDEX IF NOT EXISTS idx_inscripciones_torneo_torneo_perfil ON public.inscripciones_torneo(torneo_id, perfil_id);
CREATE INDEX IF NOT EXISTS idx_inscripciones_torneo_perfil_estado ON public.inscripciones_torneo(perfil_id, estado);

-- 6. Verificación final
DO $$
DECLARE
    table_exists BOOLEAN;
    column_count INTEGER;
BEGIN
    SELECT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_name = 'inscripciones_torneo' AND table_schema = 'public'
    ) INTO table_exists;
    
    SELECT COUNT(*) INTO column_count
    FROM information_schema.columns 
    WHERE table_name = 'inscripciones_torneo' AND table_schema = 'public';
    
    RAISE NOTICE '=== VERIFICACIÓN FINAL ===';
    RAISE NOTICE 'Tabla inscripciones_torneo existe: %', table_exists;
    RAISE NOTICE 'Número de columnas: %', column_count;
    
    IF table_exists THEN
        RAISE NOTICE 'Columnas de inscripciones_torneo:';
        FOR column_rec IN 
            SELECT column_name, data_type, is_nullable 
            FROM information_schema.columns 
            WHERE table_name = 'inscripciones_torneo' AND table_schema = 'public'
            ORDER BY ordinal_position
        LOOP
            RAISE NOTICE '  - %: % (nullable: %)', 
                column_rec.column_name, 
                column_rec.data_type, 
                column_rec.is_nullable;
        END LOOP;
    END IF;
    
    RAISE NOTICE '=== LISTO PARA INSCRIPCIONES ===';
END $$;

-- 7. Grant permissions
GRANT ALL ON public.inscripciones_torneo TO authenticated;
GRANT SELECT ON public.inscripciones_torneo TO anon;
